import { layout } from "../layout.mjs";

/**
 * The privacy notice.
 *
 * Written from what the code actually stores — the tables and columns are real
 * and were read off the schema, not adapted from a template. A privacy notice
 * that describes data a product doesn't hold is worse than none: it is the
 * document a district's counsel reads most carefully, and any gap between it
 * and the software is the thing that ends an adoption.
 *
 * It is a draft for counsel, not a substitute for one. Two things in
 * particular are business decisions rather than engineering ones and are
 * marked where they appear: the retention periods, and whether a signed data
 * processing agreement is offered as standard.
 */

const UPDATED = "8 September 2026";

export default () =>
  layout({
    path: "/privacy",
    title: "Privacy notice",
    description:
      "What Notesanity collects, why, who can see it, and how schools and families exercise their rights — written for FERPA and COPPA obligations in schools.",
    body: `
<section>
  <div class="wrap">
    <div class="doc">
      <p class="eyebrow">Legal</p>
      <h1>Privacy notice</h1>
      <p class="updated">Last updated ${UPDATED}</p>

      <p class="lede">
        Notesanity is used by schools, and most of the people in it are children. This notice
        says exactly what we hold, why we hold it, and what we will never do with it.
      </p>

      <div class="callout">
        <p><b>The short version.</b> We store the schoolwork students make and the accounts that
        make it. We do not sell it, we do not advertise, and we do not build profiles of children.
        We hold it on behalf of the school, and the school decides what happens to it.</p>
      </div>

      <div class="toc">
        <b>On this page</b>
        <ol>
          <li><a href="#role">Our role, and the school's</a></li>
          <li><a href="#collect">What we collect</a></li>
          <li><a href="#never">What we never do</a></li>
          <li><a href="#ferpa">FERPA</a></li>
          <li><a href="#coppa">COPPA and children under 13</a></li>
          <li><a href="#sharing">Who else processes it</a></li>
          <li><a href="#retention">How long we keep it</a></li>
          <li><a href="#security">How it is protected</a></li>
          <li><a href="#rights">Access, correction and deletion</a></li>
          <li><a href="#changes">Changes, and contact</a></li>
        </ol>
      </div>

      <h2 id="role">1. Our role, and the school's</h2>
      <p>
        When a school uses Notesanity, <b>the school is the controller of its students' data and we
        are the processor</b>. We hold and process student records on the school's instruction and
        for the school's purposes, and for nothing else. The school decides who has an account, what
        is taught, what is kept and what is deleted; we carry that out.
      </p>
      <p>
        Practically: we will not use a student's work to train models, to market anything, or to
        build a profile that follows them. If a school tells us to delete its data, we delete it.
      </p>

      <h2 id="collect">2. What we collect</h2>
      <p>Everything below is either given to us by the school, created by a user inside the app, or
      generated by the app to make it work. There is no third-party tracking of any kind.</p>

      <h3>Account information</h3>
      <table>
        <tr><th>What</th><th>Why</th></tr>
        <tr><td>Email address</td><td>Identifies the account and is how sign-in links are sent</td></tr>
        <tr><td>Name</td><td>So teachers and classmates see a person, not an address</td></tr>
        <tr><td>Profile picture</td><td>Only if you sign in with Google, which supplies it</td></tr>
        <tr><td>Role and school</td><td>Decides what you can see — a teacher's view differs from a student's</td></tr>
        <tr><td>Last sign-in time</td><td>So a school admin can see which accounts are actually in use</td></tr>
      </table>

      <h3>Schoolwork</h3>
      <table>
        <tr><th>What</th><th>Why</th></tr>
        <tr><td>Handwriting and drawing</td><td>The work itself — stored as the strokes that were drawn</td></tr>
        <tr><td>Typed answers, checkboxes, dropdowns</td><td>The work itself</td></tr>
        <tr><td>Images and audio a student uploads</td><td>Answers given as a photo or a recording</td></tr>
        <tr><td>Documents a teacher uploads</td><td>The notebooks they build lessons from</td></tr>
        <tr><td>Grades, feedback and marking</td><td>Assessment, visible to the student and their teachers</td></tr>
        <tr><td>Edit history</td><td>Who changed what and when, so a teacher can see how work progressed</td></tr>
      </table>

      <h3>Operational records</h3>
      <table>
        <tr><th>What</th><th>Why</th></tr>
        <tr><td>Sign-in sessions</td><td>A random identifier in a cookie. It contains no personal data.</td></tr>
        <tr><td>Failed requests</td><td>Method, path, status and account, kept only for the most recent 500 failures, to diagnose faults. Successful requests are not logged.</td></tr>
        <tr><td>Email delivery records</td><td>Address, type and outcome, so we can tell you whether a sign-in link was actually sent</td></tr>
      </table>

      <h3>Passwords and sign-in tokens</h3>
      <p>
        If an account uses a password, we store it only as a PBKDF2-SHA256 hash with a per-account
        salt — we cannot read it or recover it, and neither can anyone who obtains the database.
        Sign-in links are stored only as SHA-256 hashes of single-use tokens that expire after 20
        minutes, so a copy of our database cannot be replayed as a login.
      </p>

      <h2 id="never">3. What we never do</h2>
      <ul>
        <li><b>We do not sell personal information</b>, and we never will.</li>
        <li><b>We do not serve advertising</b> and do not allow anyone else to.</li>
        <li><b>We do not use student work to train machine-learning models.</b></li>
        <li><b>We do not use third-party analytics or advertising trackers.</b> There are no
            tracking cookies in Notesanity; the only cookie is the one that keeps you signed in.</li>
        <li><b>We do not build behavioural profiles</b> of students, or track them across sites.</li>
      </ul>

      <h2 id="ferpa">4. FERPA</h2>
      <p>
        Student work and grades in Notesanity are education records under the Family Educational
        Rights and Privacy Act. We handle them as a <b>school official with a legitimate educational
        interest</b> under 34 CFR §99.31(a)(1)(i)(B):
      </p>
      <ul>
        <li>We perform a function the school would otherwise perform itself.</li>
        <li>We are under the school's direct control as to the use and maintenance of the records.</li>
        <li>We use the records only for the purpose they were disclosed for, and do not re-disclose
            them except as the school directs or the law requires.</li>
      </ul>
      <p>
        Parents' rights to inspect, review and request correction of their child's records are
        exercised through the school, which can reach every record we hold for that child. We help
        schools answer those requests.
      </p>

      <h2 id="coppa">5. COPPA and children under 13</h2>
      <p>
        Notesanity is used by children under 13. We collect personal information from them only in
        the educational context the school has directed, and we rely on the school to provide
        consent on parents' behalf — the approach the Federal Trade Commission permits where a
        service is used solely for a school's educational purpose and the information is used for no
        commercial purpose.
      </p>
      <p>To make that reliance honest, we hold ourselves to the following:</p>
      <ul>
        <li>We collect no more from a child than the app needs to work.</li>
        <li>We ask children for nothing beyond their schoolwork and the account details the school
            already holds. There is no public profile, no messaging between students, and nothing a
            child can make visible to the wider internet.</li>
        <li>We never use a child's information for advertising, marketing or profiling.</li>
        <li>A school or parent (through the school) can review a child's information and have it
            deleted; see <a href="#rights">access, correction and deletion</a>.</li>
      </ul>
      <p>
        Schools: you are responsible for telling parents which services you have engaged and what
        they collect. We will give you whatever detail you need for that notice — ask us.
      </p>

      <h2 id="sharing">6. Who else processes it</h2>
      <p>We keep the list of companies that touch this data as short as we can.</p>
      <table>
        <tr><th>Who</th><th>What for</th><th>What they see</th></tr>
        <tr><td>Cloudflare</td><td>Hosting, database, file storage and sending our email</td>
            <td>All data, as our infrastructure provider</td></tr>
        <tr><td>Google</td><td>Optional "Sign in with Google"</td>
            <td>That an account signed in. Only if that method is used.</td></tr>
      </table>
      <p>
        When a teacher imports a Word or PowerPoint file, or picks a file out of Google Drive, that
        conversion happens in their own browser with their own Google account. The file reaches us
        only as the finished PDF; we never hold Google credentials.
      </p>
      <p>
        We do not transfer personal information to anyone else, except where the law requires it. If
        Notesanity were ever acquired, student data would remain subject to this notice, and schools
        would be told before any change of control took effect.
      </p>

      <h2 id="retention">7. How long we keep it</h2>
      <table>
        <tr><th>What</th><th>Kept</th></tr>
        <tr><td>Schoolwork, notebooks and grades</td><td>While the school's account is open, unless the school deletes them sooner</td></tr>
        <tr><td>Account details</td><td>While the account exists</td></tr>
        <tr><td>Sign-in sessions</td><td>30 days, then expired and removed</td></tr>
        <tr><td>Sign-in links</td><td>20 minutes, and single use</td></tr>
        <tr><td>Failure logs</td><td>The most recent 500 entries only</td></tr>
        <tr><td>Email delivery records</td><td>The most recent 500 entries only</td></tr>
      </table>
      <p>
        When a school asks us to delete its data, we remove it from our live systems within 30 days.
        Backups age out on their own cycle and are never restored to bring deleted data back.
      </p>

      <h2 id="security">8. How it is protected</h2>
      <ul>
        <li>Everything travels over TLS. The app is served only over HTTPS.</li>
        <li>Passwords are hashed with PBKDF2-SHA256 and a per-account salt, and compared in a way
            that does not leak how much of a guess was right.</li>
        <li>Session cookies are HttpOnly and Secure, so page scripts cannot read them.</li>
        <li>Access is enforced per request, not per screen: a student can only ever reach their own
            work, and a teacher only their own classes'.</li>
        <li>Handed-in work is frozen, so it cannot be altered after a teacher has seen it.</li>
        <li>Each school's data is separated, and a person from one school cannot reach another's.</li>
      </ul>
      <p>
        No system is perfect. If we discover a breach affecting a school's data, we will tell that
        school without undue delay, with what we know and what we are doing about it.
      </p>

      <h2 id="rights">9. Access, correction and deletion</h2>
      <p>
        <b>Students and parents:</b> ask your school. Because the school controls the records, it is
        the school that decides and instructs us, and it can reach everything we hold about a child.
      </p>
      <p>
        <b>Schools:</b> email <a href="mailto:support@notesanity.com">support@notesanity.com</a> from
        a school address for a copy of your data, a correction, or deletion of a student's or the
        whole school's records. Any notebook can also be exported to PDF from inside the app at any
        time, without asking us.
      </p>
      <p>
        Depending on where you are, you may have further rights over personal information — to
        object, to restrict processing, or to complain to a regulator. We will honour them; contact
        us and we will route the request with your school.
      </p>

      <h2 id="changes">10. Changes, and contact</h2>
      <p>
        If we change this notice in a way that affects what we collect or who sees it, we will tell
        schools using Notesanity before it takes effect — not silently update the date at the top.
      </p>
      <p>
        Questions, requests, or paperwork your district needs signed:
        <a href="mailto:support@notesanity.com">support@notesanity.com</a>.
      </p>
    </div>
  </div>
</section>`,
  });
